[package]
name = "food2fuel-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
sqlx = { version = "0.5", features = ["postgres", "macros"] }
dotenv = "0.15.0"
